### ISSUE TITLE
 Opencas initialization failed after unexpected server power loss.

### ISSUE THREAD

**Issue by yaleisnotavailable** [Open-CAS/open-cas-linux#553] opened 2020-10-21 01:37 UTC
## Question
 my partner AiShu reported this question. this problem can reproduce. in Aishu's test, each time they unplugged the power cord of the server and power server again, they confront  a failure " Opencas initialization failed. Couldn’t add device /dev/disk/by-id/wwn-0x6700…… as core 1 in cache 1". i put test environment, steps to reproduce this issue, logs they got in the attachment. would you please take a look? 
thanks much 
yale

## Your Environment

* OpenCAS version (commit hash or tag):
* Operating System:
* Kernel version:
* Cache device type (model):
* Core device type (model):
* Cache configuration:
* * Cache mode: (default: wt)
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)
[after unexpected power lose.pdf](https://github.com/Open-CAS/open-cas-linux/files/5412666/after.unexpected.power.lose.pdf)

**Comment by gwnet** [comment] 2020-10-21 07:19
@yaleisnotavailable, could you please help on below questions
this issue repeatable or only one time thing?
please fill the open-cas version and kernel version?
if user manually kill casadm process during the test?

**Comment by yaleisnotavailable** [comment] 2020-10-21 10:21
1.	opencas version : release  20.03.01.00000907 
2.	kernel version : centos7.5 x86 ， upgrade kernel to 5.4.40
3.	100% reproduced
4.	not kill casadm manually.

thanks

**Comment by arutk** [comment] 2020-10-22 09:51
Hi @yaleisnotavailable. We took a look at your logs. Looks like the problem is udev rule timeout, resulting in failure to load cache. 

There are two potential ways to workaround this. The first thing that comes to my mind is incrementing timeout for udev rules processing to more than 120s. This would be a matter of changing system configuration. I don't know exactly if this is possible, we will need to look into udev configuration options for this

If it turns out to be impossible to achieve this effect in udev, we will have a workaround implemented in the nearest hotfix update (20.3.3).

**Comment by imjfckm** [comment] 2020-10-22 12:10
@yaleisnotavailable , you could try extending the `event_timeout` by modifying `udev.conf` file (as per documentation here: https://www.freedesktop.org/software/systemd/man/udev.conf.html).

Also, as @arutk mentioned - in v20.3.3 there will be last-resort attempt at setting up the configuration in `open-cas.service` with default timeout of 30 minutes - that should solve your problem.

**Comment by yaleisnotavailable** [comment] 2020-10-23 00:31
thanks thanks and thanks! 
will try it soon and give feedback here. 
have a great day !
yale

**Comment by katlapinka** [comment] 2020-11-19 10:37
We assume that our recommendations works fine because there is no update for this issue for a long time, so I am closing this. Please let us know, if the problem will still occur.

**Closed by katlapinka** 2020-11-19 10:37 UTC
Labels: bug, question

**Comment by yaleisnotavailable** [comment] 2020-11-22 23:55
thanks gentleman. please go ahead to close this call. the customer paused to try openCAS. so i have no progress. 
thanks again and have a great day to you. 
yale
