### ISSUE TITLE
CAS hangs after file operations with filesystems ext3, xfs

### ISSUE THREAD

**Issue by karolinavelkaja** [Open-CAS/open-cas-linux#1228] opened 2022-06-13 09:15 UTC
## Description
tests: 
test_interrupt_cache_mode_switch_delayed
test_interrupt_cache_mode_switch_immediately
iteration details:
![image](https://user-images.githubusercontent.com/71020523/173320782-bc3ccf63-cf1e-4286-8a2e-1b51eac3a922.png)
or
![image](https://user-images.githubusercontent.com/71020523/173320856-e72e9759-fd8e-4144-9aa1-84ec74cae685.png)
general/master log:
![image](https://user-images.githubusercontent.com/71020523/173321018-21fb5eb0-6ebd-41bc-8d08-7a1ea8c5da5d.png)

## Steps to Reproduce
screenshots attached above.

## Logs
[2022_06_10_18_00_05_test_interrupt_cache_mode_switch_delayed.zip](https://github.com/Open-CAS/open-cas-linux/files/8889696/2022_06_10_18_00_05_test_interrupt_cache_mode_switch_delayed.zip)
[2022_06_10_18_01_54_test_interrupt_cache_mode_switch_delayed.zip](https://github.com/Open-CAS/open-cas-linux/files/8889697/2022_06_10_18_01_54_test_interrupt_cache_mode_switch_delayed.zip)

## Your Environment

* OpenCAS version (commit hash or tag): 22.06.0.0696.master
* Operating System: Centos 7.9
* Kernel version: 5.15
* Cache device type (NAND/Optane/other):
* Core device type (HDD/SSD/other):
* Cache configuration:
* * Cache mode: (default: wt)
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

**Comment by jfckm** [comment] 2022-06-13 09:28
kernel bug with same stack trace as in #1224 - duplicate

**Comment by jfckm** [comment] 2022-06-15 12:13
Duplicate of #1224

**Closed** 2022-06-15 12:12 UTC
Labels: bug
