### ISSUE TITLE
kernel BUG at cas_cache module: /eviction/lru.c:151

### ISSUE THREAD

**Issue by karolinavelkaja** [Open-CAS/open-cas-linux#729] opened 2021-03-15 13:52 UTC
## Description
After disabling cleaning and sequential cutoff and then running IO on CAS device kernel bug occurred.

## Expected Behavior
running IO successfully.

## Actual Behavior
Kernel BUGs - system breakdown

## Steps to Reproduce
test_concurrent_flushes.py
1. prepare caches (3) and cores (3)
2. start caches
3. disable cleaning and sequential cutoff
4. add core devices to caches
5. run workload on each CAS devices ( with dd)

## Logs
[serial.log](https://github.com/Open-CAS/open-cas-linux/files/6141774/serial.log)

## Your Environment
* OpenCAS version (commit hash or tag): 21.03.0.0468.master a70a862
* Operating System: RHEL 8.3
* Kernel version: 4.18.0-240.el8.x86_64
* Cache device type (NAND/Optane/other): Optane, NAND
* Core device type (HDD/SSD/other): HDD

**Comment by Deixx** [comment] 2021-03-16 12:15
Duplicate of https://github.com/Open-CAS/open-cas-linux/issues/728

**Closed** 2021-03-17 11:02 UTC
Labels: bug, duplicate
